UIDAI/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('update/',include("update.urls")),
    path('aadharcard/',include("aadharcard.urls")),
    url(r'^captcha/', include('captcha.urls')),
    path('nearest_centre/',views.nearest_centre,name = 'nearest_centre'),
    path('',views.uidai_home,name = 'uidai_home')
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

update/urls.py
from django.urls import path
from . import views

app_name = "update"

urlpatterns = [
    path('address/',views.update_address,name='update_address'),
    path('address/otp',views.verify_otp,name='verify_otp'),
    path('address/data_update_req',views.data_update_req,name='data_update_req'),
    path('address/data_modify',views.data_modify,name='data_modify'),
    path('address/proceed',views.proceed,name='proceed'),
    path('address/submit_document',views.submit_document,name='submit_document')
]

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "UIDAI"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('update/',include("update.urls")),
    path('aadharcard/',include("aadharcard.urls")),
    url(r'^captcha/', include('captcha.urls')),
    path('nearest_centre/',views.nearest_centre,name = 'nearest_centre'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

update/models.py
from django.db import models

# Create your models here.

update/forms.py
from django import forms
from captcha.fields import CaptchaField

class updateAddressForm(forms.Form):
    co = forms.CharField(label = 'C/O:')
    house = forms.CharField(label = 'House/Apt.:')
    street = forms.CharField(label = 'Street/Road:')
    landmark = forms.CharField(label = 'Landmark:')
    area = forms.CharField(label = 'Area/locality:')
    pincode = forms.IntegerField(label = 'Pincode:')
    town = forms.CharField(label = 'Village/Town/City:')
    po = forms.CharField(label = 'P.O.:')
    district = forms.CharField(label = 'District:')
    state = forms.CharField(label = 'State:')
    class Meta:
        fields = ('co','house','street','landmark','area','pincode','town','po','district','state')

class captcha(forms.Form):
    #myfield = AnyOtherField()
    captcha = CaptchaField()

update/views.py
from django.shortcuts import render
from .forms import updateAddressForm,captcha
from django.http import HttpResponse
from django.db import connection
import requests
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from bs4 import BeautifulSoup
import random
"""
class Sms:

	def __init__(self, mobileNo, password):

		'''
		Takes mobileNo and password as parameters for constructors and try to log in
		'''

		self.base_url = "http://www.way2sms.com/"
		self.login_url = self.base_url + "re-login"
		self.msg_url=  self.base_url + "smstoss"
		self.future_msg_url = self.base_url + "schedulesms"
		self.logout_url = self.base_url + "Logout"

		self.session = requests.Session()	# Session because we want to maintain the cookies
		self.session.headers['User-Agent'] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
		self.session.get(self.base_url)		# once do a http GET to get the cookies

		#self.session.headers['Referer'] = self.base_url
		#self.session.headers['Host'] = self.base_url
		self.session.headers['X-Requested-With'] = 'XMLHttpRequest'
		#self.session.headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8'
		#self.session.headers['Content-Length'] = '43'
		self.set_cookies_header()

		self.payload = {'mobileNo': mobileNo, 'password': password, 'CatType' : ''}
		self.q = self.session.post(self.login_url, data=self.payload)		# POST the payload
		self.logged_in = False				# a variable of knowing whether logged in or not

		if self.q.status_code == 200 and self.q.text == "send-sms":	# http status 200 == OK
			print("Successfully logged in..!")
			self.logged_in=True
		else:
			print("Can't login, once check credential..!")
			self.logged_in=False

		self.jsid = self.session.cookies.get_dict()['JSESSIONID'][4:]	    # JSID is the main KEY as JSID are produced every time a session satrts

	def set_cookies_header(self):
		self.session.headers['Cookie'] = "JSESSIONID=" + self.session.cookies.get_dict()['JSESSIONID']

	def msgSentToday(self):

		'''
		Returns number of SMS sent today as there is a limit of 100 messages everyday..!
		'''

		if self.logged_in == False:
			print("Can't perform since NOT logged in..!")
			return -1

		self.msg_left_url='http://www.way2sms.com/sentSMS?Token='+self.jsid
		self.q=self.session.get(self.msg_left_url)
		self.soup=BeautifulSoup(self.q.text,'html.parser')		#we want the number of messages sent which is present in the
		self.t=self.soup.find("div",{"class":"hed"}).h2.text		# div element with class "hed" -> h2
		self.sent=0

		for self.i in self.t:
			if self.i.isdecimal():
				self.sent=10*self.sent+int(self.i)
		return self.sent

	def send(self,mobile_no,msg):

		'''
		Sends the message to the given mobile number
		'''

		if self.logged_in == False:
			print("Can't perform since NOT logged in..!")
			return False

		if len(msg)>139 or len(str(mobile_no))!=10 :	#checks whether the given message is of length more than 139 and mobile numnber is valid
			return False

		self.payload = {
						'ssaction':'ss',
						'Token':self.jsid,					#inorder to visualize how I came to these payload,
			        	'toMobile':mobile_no,			#must see the NETWORK section in Inspect Element
       				 	'message':msg,						#while messagin someone from your browser
       			    }

		self.q=self.session.post(self.msg_url,data=self.payload)

		if self.q.status_code==200 and self.q.text == '0':
			return True
		else:
			return False

	def send_later(self, mobile_no, msg, date, time):				#Function for future SMS feature.
											#date must be in dd/mm/yyyy format
											#time must be in 24hr format. For ex: 18:05

		if self.logged_in == False:
			print("Can't perform since NOT logged in..!")
			return False

		if len(msg)>139 or len(mobile_no)!=10 or not mobile_no.isdecimal():
			return False

		dateparts = date.split('/')			#These steps to check for valid date and time and formatting
		timeparts = time.split(':')
		if int(dateparts[0])<1 or int(dateparts[0])>32 or int(dateparts[1])>12 or int(dateparts[1])<1 or int(dateparts[2])<2017 or int(timeparts[0])<0 or int(timeparts[0])>23 or int(timeparts[1])>59 or int(timeparts[1])<0:
			return False
		date = dateparts[0].zfill(2) + "/" + dateparts[1].zfill(2) + "/" + dateparts[2]
		time = timeparts[0].zfill(2) + ":" + timeparts[1].zfill(2)

		self.payload = {'Token' : self.jsid,
						'toMobile' : mobile_no,
						'sdate' : date,
						'stime' : time,
						'message' : msg,
					}

		self.q = self.session.post(self.future_msg_url, data=self.payload)
		if self.q.status_code == 200:
			return True
		else:
			return False

	def logout(self):
		self.session.get(self.logout_url)
		self.session.close()								# close the Session
		self.logged_in=False
"""
class smsender():



    def __init__(self):

        self.auth_token = '3BwxGQMoVlPuay1EW9iksqOhrFKSnt8HzCD0m7IRZ45pAbfeXL2DosgtX1fTIJB8knv6LYhRA0e9plGb'

        # self.smssid = 'AC454dda9e0468a8be7ed47a7121e44afe'

        # self.smsauth_token = 'b52f1033669b39e26ed3fe9978be015b'

        self.sms_url = "https://www.fast2sms.com/dev/bulk"

        # self.smsclient = Client(self.smssid, self.smsauth_token)

        # self.smsnum = '+18608965907'



    def send_sms(self,data,phno):

        payload = "sender_id=FSTSMS&message={}&language=english&route=p&numbers={}".format(data,phno)

        print(payload)

        headers = {

            'authorization': self.auth_token,

            'Content-Type': "application/x-www-form-urlencoded",

            'Cache-Control': "no-cache",

            }

        response = requests.request("POST", self.sms_url, data=payload, headers=headers)

        print(response.text)

        print("sms sent")

cursor = connection.cursor()

def update_address(request):
	if request.method == 'POST':
		form = captcha(request.POST)
		if form.is_valid():
			aadhar_num = request.POST['aadhar_num']
			cursor.execute("SELECT phone FROM details WHERE aadhar_num={}".format(aadhar_num))
			phone_num=cursor.fetchone()
			#a = Sms('9121587454','Shiva@01')
			smss = smsender()
			otp=random.randint(100000,999999)
			phone_num=phone_num[0]
			print(phone_num)
			print(type(phone_num))
			#send(phone_num,str(otp))
			smss.send_sms(otp, phone_num)
			print(phone_num)
			print(otp)
			cursor.execute("INSERT INTO verify_otp VALUES ({},{},{})".format(aadhar_num,phone_num,otp))
			return render(request,"update/enter_otp.html",{'phone_num': phone_num})
	else:
		form = captcha()
	return render(request,"update/enter_aadharnum.html",{'form':form})


def verify_otp(request):
	if request.method == 'POST':
		otp = request.POST['otp']
		phone_num = request.POST['phone_num']
		cursor.execute("SELECT otp,aadhar_num FROM verify_otp WHERE phone_num={}".format(phone_num))
		real_otp = cursor.fetchone()
		if int(otp) == int(real_otp[0]) :
			cursor.execute("DELETE FROM verify_otp WHERE phone_num={}".format(phone_num))
			return render(request,"update/data_update_req.html",{'aadhar_num':real_otp[1]})
		else:
			return HttpResponse('NO')

def data_update_req(request):
	if request.method == 'POST':
		form = updateAddressForm()
		aadhar_num = request.POST['aadhar_num']
		return render(request,"update/contact_details.html",{'form':form,'aadhar_num':aadhar_num})

def data_modify(request):
	if request.method == 'POST':
		form = updateAddressForm(request.POST)
		aadhar_num = request.POST['aadhar_num']
		co = form.data['co']
		house = form.data['house']
		street = form.data['street']
		landmark = form.data['landmark']
		area = form.data['area']
		pincode = form.data['pincode']
		town = form.data['town']
		postoffice = form.data['po']
		dist = form.data['district']
		state = form.data['state']
		cursor.execute("INSERT INTO update_req VALUES ({},'{}','{}','{}','{}','{}',{},'{}','{}','{}','{}')".format(aadhar_num,co,house,street,landmark,area,pincode,town,postoffice,dist,state))
		return render(request,"update/modify_details.html",{'form':form,'aadhar_num':aadhar_num})

def proceed(request):
	if request.method == 'POST':
		aadhar_num = request.POST['aadhar_num']
		return render(request,"update/document_upload.html",{'aadhar_num':aadhar_num})

def submit_document(request):
	if request.method == 'POST':
		aadhar_num = request.POST['aadhar_num']
		proof_type = request.POST['type']
		"""if 'proof' in request.FILES and request.POST:
			filename = request.FILES['proof'].name
			return HttpResponse(filename)
		else:
			return HttpResponse('no')"""
		image = request.FILES['proof']
		fs_img = FileSystemStorage(
		        location = settings.FS_IMAGE_UPLOADS,
		        base_url= settings.FS_IMAGE_URL
		    )
		imageName = fs_img.save(image.name,image)
		uploaded_image_url = fs_img.url(imageName)
		print(uploaded_image_url)
		image_url = 'http://127.0.0.1:8000'+uploaded_image_url
		print(image_url)
		cursor.execute("INSERT INTO document VALUES ({},'{}','{}')".format(aadhar_num,proof_type,image_url))
		return render(request,'update/thanku.html')

update/templates/update/contact_details.html
{% extends 'test.html' %}
{% block content %}
  <div class="container">
    <center><h5>Enter data for update</h5></center>
    <div class="card hoverable">
      <div class="card-content">
        <p>
            Submit your details in the form below. Ensure that your information is
            transliterated correctly in the local language. The English spellings in the
            local language boxes may be modified to get the local language spelling
            correctly. Detailed guidelines on local language transliteration are available <br>
        </p>
        <b>Contact Details:</b>
        <form class="" action="{% url 'update:data_modify' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="aadhar_num" value="{{ aadhar_num }}">
          {{ form }}
          <div class="card-content grey lighten-4">
            <button type="submit" name="button" class="waves-effect waves-light btn Center">Submit update request</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

update/templates/update/data_update_req.html
{% extends 'test.html' %}
{% block content %}
  <div class="container">
    <center><h5>Select field(s) to update</h5></center>
    <div class="card hoverable">
      <div class="card-content">

        <form class="" action="{% url 'update:data_update_req' %}" method="post">
          {% csrf_token %}
          <fieldset>
            <legend>Local language: Telugu</legend>
            <b>Have address proof:</b>
              <input type="checkbox" id="address_proof">
              <label for="address_proof"></label>
            <input type="hidden" name="aadhar_num" value="{{ aadhar_num }}">
            <div class="card-content grey lighten-4">
              <button type="submit" name="button" class="waves-effect waves-light btn Center">Submit</button>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

update/templates/update/document_upload.html
{% extends 'test.html' %}
{% block content %}
  <div class="container">
    <center><h5>Update Address Online</h5></center>
    <div class="card hoverable">
      <div class="card-content">

        <form class="" action="{% url 'update:submit_document' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <b>Proof of address:</b>
          <input type="hidden" name="aadhar_num" value="{{ aadhar_num }}">
          <div class="input-field col s12">
          <div class="">
            <select class="browser-default" name="type">
              <option value="passport">Passport</option>
              <option value="voterid">Voter_id</option>
              <option value="rationcard">Ration card</option>
              <option value="license">Driving License</option>
          </select>
          </div>
          <script>
            document.addEventListener('DOMContentLoaded', function() {
              var elems = document.querySelectorAll('select');
              var instances = M.FormSelect.init(elems, options);
            });
          </script>
          </div>
          <b>Select file and upload:</b>
          <input type="file" name="proof" accept="image/*">
          <div class="card-content grey lighten-4">
            <button type="submit" name="button" class="waves-effect waves-light btn Center">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

update/templates/update/enter_aadharnum.html
{% extends 'test.html' %}
{% block content %}
  <div class="container">
    <center><h5>Update Address Online</h5></center>
    <div class="card hoverable">
      <div class="card-content">

        <form class="" action="{% url 'update:update_address' %}" method="post">
            {% csrf_token %}
            <b>Enter aadhar number:</b>
            <input type="number" name="aadhar_num" value="">
            {{ form }}
            <div class="card-content grey lighten-4">
              <button type="submit" name="button" class="waves-effect waves-light btn Center">Send otp</button>
            </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

update/templates/update/enter_otp.html
{% extends 'test.html' %}
{% block content %}
  <div class="container">
    <div class="card hoverable">
      <div class="card-content">

        <form class="" action="{% url 'update:verify_otp' %}" method="post">
          {% csrf_token %}
          <b>Enter received otp:</b>
          <input type="hidden" name="phone_num" value="{{ phone_num }}">
          <input type="number" name="otp" value="">
          <div class="card-content grey lighten-4">
            <button type="submit" name="button" class="waves-effect waves-light btn Center">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

update/templates/update/modify_details.html
{% extends 'test.html' %}
{% block content %}
  <div class="container">
    <center><h5>Update Address Online</h5></center>
    <div class="card hoverable">
      <div class="card-content">

        <form class="" action="{% url 'update:proceed' %}" method="post">
          <input type="hidden" name="aadhar_num" value="{{ aadhar_num }}">
          {% csrf_token %}
          {% for field in form %}
            {{ field.label_tag }}
            {{ field.value }}<br>
          {% endfor %}
          <div class="card-content grey lighten-4">
            <button type="submit" name="proceed" class="waves-effect waves-light btn Center">Proceed</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

update/templates/update/thanku.html
{% extends 'test.html' %}
{% block content %}
<div class="card hoverable">
  <div class="card-content">
    <h2>Your request for the address update will be reviewed and updated within 15 days if they are relevant</h2>
  </div>
</div>
{% endblock %}