UIDAI/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('update/',include("update.urls")),
    path('aadharcard/',include("aadharcard.urls")),
    url(r'^captcha/', include('captcha.urls')),
    path('nearest_centre/',views.nearest_centre,name = 'nearest_centre'),
    path('',views.uidai_home,name = 'uidai_home')
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = "service"

urlpatterns = [

    url(r'^update_verify/$',views.update_verify, name="update_verify"),
    url(r'^check_update_status/$',views.get_update_status, name="check_update_status"),
    #url(r'^complaint/$',views.complaint, name="complaint"),
    url(r'^complaint_front/$',views.complaint_front, name="complaint_front"),
    #url(r'^check_enroll_id/$', views.check_enroll_id, name='check_enroll_id'),
    #url(r'^autofill1_check/$', views.autofill1_check, name='autofill1_check'),
    url(r'^complaint/$', views.complaint, name='autofill1'),
    url(r'^check_enroll_id/$', views.check_enroll_id, name='check_enroll_id'), # check weather enroll_id in complaint form exsists or not
    url(r'^autofill1_check/$', views.autofill1_check, name='autofill1_check'),
    url(r'^complaint_status/$', views.complaint_status, name='complaint_status'),

    url(r'^verify_aadhar/$', views.verify_aadhar, name='verify_aadhar'), # verify aadhar eists or not
    url(r'^verify_mobile_email/$', views.verify_mobile_mail, name='verify_mobile_mail'),
    url(r'^verify_otp/$', views.verify_otp, name='verify_otp'),

    url(r'^offline_ekyc/$', views.offline_ekyc, name='offline_ekyc'),
    url(r'^offline_ekyc_otp/$', views.offline_ekyc_otp, name='offline_ekyc_otp'),

    url(r'^address_status/$', views.address_status, name='address_status'),
    url(r'^address_status_result/$', views.address_status_result, name='address_status_result'),

    url(r'^bank_linking/$', views.bank_linking, name='bank_linking'),
    url(r'^bank_linking_otp/$', views.bank_linking_otp, name='bank_linking_otp'),
    #url(r'^complaint_status/$', views.complaint_status_resu, name='complaint_status_result'),


]

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "UIDAI"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('update/',include("update.urls")),
    path('aadharcard/',include("aadharcard.urls")),
    url(r'^captcha/', include('captcha.urls')),
    path('nearest_centre/',views.nearest_centre,name = 'nearest_centre'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/1.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="" method="post">
      Enrollment ID:<input type="number" name="enrolled_ID" id="enrolled_ID" maxlength="12" required="True"/>
      Enrollment Time:
      Security Code:{{ form }}
    </form>
  </body>
</html>

templates/address_status_result.html
{% extends 'test.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <center><h5>Address update Status:</h5><center>
    <div class="col s12 m7">
      <div class="card horizontal">
        <div class="card-image">
          {% if verify %}
            <img src="{% static 'images/success.png' %}" style="height: 150px; width:150px">
          {% else %}
            <img src="{% static 'images/reject.svg' %}" style="height: 150px; width:150px">
          {% endif %}
        </div>
        <div class="card-stacked">
          <div class="card-content">
            Aadhar Number: {{status.0}} <br/>
            {% if verify %}
              Status: {{msg}} <br/>
            {% else %}
              Status: {{msg1}}
            {% endif %}
            <h6> <u>Details:</u> </h6>
              Address:  {{update_details.0}}<br>
              pin code: {{update_details.1}}
          </div>
          <div class="card-action">
            <center>  <a href="#">Update Address</a> </center>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/bank_link_otp.html
{% extends 'test.html' %}

{% block content %}
  <div class="container">
    <h5>Bank Linking Status:</h5>
    <div class="card hoverable">
      <div class="card-content">
        <form class="" action='{% url "service:bank_linking_otp" %}' method="post">
          {% csrf_token %}
          <input type="hidden" name="aadhar_num" value="{{aadhar_num}}" id="Aadhar_num" maxlength="16" required="True">
          Enter otp: <input type="number" name="otp" id="otp">
          <div class="card-content grey lighten-4">
            <button type="submit" name="button" class="waves-effect waves-light btn Center">Verify</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/bank_link_status.html
{% extends 'test.html' %}

{% block content %}
  <div class="container">
    <h5>Bank Linking Status:</h5>
    <div class="card hoverable">
      <div class="card-content">
        {% for i in details %}
          <div class="card-content grey lighten-4">
            Aadhar Number: {{i.1}} <br>
            Bank Account No: {{i.0}} <br>
          </div> <br>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}


{{details.0}}

templates/base.html
{% load static from staticfiles %}
{% load widget_tweaks %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> Home </title>
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script src='https://www.google.com/recaptcha/api.js'></script>
  </head>

  <script>
  $(document).ready(function(){
    $('.dropdown-trigger').dropdown();
  });
  </script>

  <style>
    .nav-content {
      background: linear-gradient(to right, #1a237e , #29b6f6);
    }
    #pic1{
      margin-left: 50px;
    }
    #pic2{
      margin-left: 850px;
    }
  </style>


  <body>
    <header>

      <nav class="nav-extended">
        <div class="nav-wrapper white">
            <img id="pic1" src="{% static 'images/pic1.jpg' %}">
            <img id="pic2" src="{% static 'images/pic2.jpg' %}">
        </div>

        <div class="nav-content" id="dropdown">
          <ul class="tabs tabs-transparent">
            <li ><a class = "dropdown-trigger" data-target='dropdown1' href="#test1">My Aadhaar</a></li>
            <li ><a href="#test2">About UIDAI</a></li>
            <li ><a href="#test2">Ecosystem</a></li>
            <li ><a href="#test4">Media&Resourses</a></li>
            <li ><a href="#test2">Contact&Support</a></li>
          </ul>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="card hoverable">
        <div class="card-content">

          <form class="" action="" method="post">
            {% csrf_token %}
            <div class="row">
              <form class="col s12">

                <div class="row">
                  <div class="input-field col s4">
                    <input placeholder="Placeholder" id="Enrolment_ID" type="text" class="validate">
                    <label for="Enrolment ID">Enrolment ID</label>
                  </div>

                  <div class="input-field col s4">
                    <input placeholder="Placeholder" id="Enrolment_Time" type="text" class="validate">
                    <label for="Time">Time</label>
                  </div>
                </div>

                <div class="row">
                  <div class="input-field col s4">
                    <input placeholder="Placeholder" id="Enter Security Code" type="text" class="validate">
                    <label for="Enter Security Code">Enter Security Code</label>
                  </div>
                  <div class="input-field col s4">

                  <!--  <div class="g-recaptcha" data-sitekey="6LffNpcUAAAAAMe4flz5CIVIRkFMiPqROLM49AiD"></div>-->
                  </div>
                </div>
              </form>
            </div>
          </form>
        </div>

        <div class="card-content grey lighten-4">
          <button type="submit" class="waves-effect waves-light btn">Check Status</button>
        </div>
      </div>
    </div>

    {% block content %}

    {% endblock %}

    <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>

                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
  </body>
</html>

templates/complaint_reply.html
{% extends 'basic_layout1.html' %}

{% block content %}
          <script src="../ckeditor/ckeditor.js"></script>
          <div class="container">
            <div class="card hoverable">
              <div class="card-content">
              <center>  <h5>Complaint Reply</h5> </center>
                <form class="" action="{% url 'complaint_reply' id %}" method="post">
                  {% csrf_token %}
                  complaint ID: {{ id }}<br/>
                  Complaint Reply:
                  <textarea name="reply" id="reply" rows="10" cols="80">

                  </textarea>
                  <div class="card-action">
                    <button type="submit" name="button">Submit</button>
                  </div>
                  <script>
                      CKEDITOR.replace( 'reply' );
                  </script>
              </form>
              </div>
            </div>
          </div>

{% endblock %}

templates/complaint_status.html
{% extends 'test.html' %}

{% block content %}
  <div class="container">
    <h5>Check Complaint Status:</h5>
    <div class="card hoverable">
      <div class="card-content">
        <form class="" action='{% url "service:complaint_status" %}' method="post">
          {% csrf_token %}
          Complaint ID: <input type="number" name="enrolled_ID" id="enrolled_ID" maxlength="16" required="True">
          Security Code: {{ form }}
          <button type="submit" name="button">Submit</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/complaint_status_result.html
{% extends 'test.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h5>Complaint Status:</h5>
    <div class="col s12 m7">
      <div class="card horizontal">
        <div class="card-image">
          {% if status %}
            <img src="{% static 'images/success.png' %}" style="height: 150px; width:150px">
          {% else %}
            <img src="{% static 'images/reject.svg' %}" style="height: 150px; width:150px">
          {% endif %}
        </div>
        <div class="card-stacked">
          <div class="card-content">
            Complaint ID: {{Complaint_id}} <br/>
            Reply on Complaint: {{Complaint_reply }} <br/>
            Complaint Status: {{ Complaint_status }}
          </div>
          <div class="card-action">
          <center>  <a href="#">Register Complaint</a> </center>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>history_page</title>


    <style>
        body{
background-color: lightblue;}

#history {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#history td, #history th {
  border: 1px solid #ddd;
  padding: 8px;
}

#history tr:nth-child(even){background-color: #f2f2f2;}

#history tr:hover {background-color: #ddd;}

#history th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #00FFFF;
  color: white;
}
</style>


</head>
<body>

<h1>Aadhar Update History</h1>
<table id="history">
    {% for row in details %}
        <tr>

            <th>Enroll_Id:&nbsp</th>
            <th>Name:&nbsp&nbsp&nbsp</th>
            <th>Mobile_number:&nbsp</th>
            <th>Mail_Id:&nbsp</th>
          <th>D.O.B:&nbsp&nbsp&nbsp</th>
            <th>Gender:&nbsp</th>

            <th>Area:&nbsp</th>
           <th> Pincode:&nbsp</th>
          <th>Date of Update:&nbsp&nbsp&nbsp</th>
        </tr>
        <tr>

           <th>
               {{ row.1 }}
           </th>
            <th>
               {{ row.2 }}
           </th>
         <th>
               {{ row.3 }}
           </th>
         <th>
               {{ row.4 }}
           </th>
         <th>
               {{ row.5 }}
           </th>
         <th>
               {{ row.6 }}
           </th>

         <th>
               {{ row.8 }}
           </th>
         <th>
               {{ row.9 }}
           </th>
         <th>
               {{ row.7 }}
           </th>
        </tr>
    {% endfor %}
</table><br>
</body>
</html>

templates/login.html
{% extends 'basic_layout1.html' %}

{% block content %}
  <div class="container">
    <center><h5>Agent Login</h5></center>
    <div class="card hoverable">
      <div class="card-content">

        <form class="site-form" action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{form}}
            <center><input type="submit" value="Login"></center>
          </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/new.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script>

      $(document).ready(function(){
        $('select').formSelect();
      });

    function check_enroll_id(element) {
    	$("#enroll_ok").hide();
    	$("#enroll_not").hide();
    	enroll_ID= $(element).val();
    	if (enroll_ID == "") {
    		return;
    	}

      $.ajax({
    		url : $(element).attr("data-url"),
    		data : {
    			"csrfmiddlewaretoken" : $(element).siblings("input[name='csrfmiddlewaretoken']" ).val(),
    			"enroll_ID":enroll_ID
    		},
    		method: "POST",
    		dataType : "json",
    		success : function (data) {
    			//console.log(data);
    			if (data.is_success) {
    				$("#enroll_ok").show();
    			} else {
    				$("#enroll_not").show();
    			}
    		}
    	});
    }


    </script>

    <script>
    function autofill1_check(element) {
    	pin_Code= $(element).val();
    	if (pin_Code == "") {
    		return;
    	}
    	$.ajax({
    		url : $(element).attr("data-url"),
    		data : {
    			"csrfmiddlewaretoken" : $(element).siblings("input[name='csrfmiddlewaretoken']" ).val(),
    			"pin_Code":pin_Code
    		},
    		method: "POST",
    		dataType : "json",
    		success : function (data) {
    			//console.log(data);
    			if (data.is_sucess) {
    				$("#city").val(data.Region);
    			}
    		}
    	});
    }
    </script>

  </head>
  <body>
    <div class="container">
      <div class="row">
        <form class="col s12 card" action='{% url "service:autofill1" %}' method="post">
          {% csrf_token %}
              <div class="row">
                <div class="input-field col s6 m6 l6">
                  <input type="number" class="validate" name="enroll_ID" id="enroll_ID" required="True" maxlength="40" onkeyup="check_enroll_id(this);return false;" data-url="{% url 'service:check_enroll_id' %}"/>
                  <label for="last_name">enrollment ID</label>
                </div>

                <div class="col s3" style="color:green;display:none;margin-top: 4px;"  id="enroll_not">
                    <span class="">Enrollment ID exsits</span>
                </div>
                <div class="col s3" style="color: red;display:none; margin-top: 4px;" id="enroll_ok">
                    <span class="glyphicon glyphicon-ok"> Enrollment ID does'nt exsits</span>
                </div>


              </div>

              <div class="row">
                <div class="input-field col s6">
                  <input type="text" name="Name" id="Name" required="True">
                  <label for="last_name">Name</label>
                </div>

                <div class="input-field col s6">
                  <input type="email" name="Email" id="Email" required="True">
                  <label for="last_name">Email</label>
                </div>

                <div class="input-field col s6">
                  <input type="number" name="Phone_No" id="Phone_No" maxlength="10" required="True">
                  <label for="last_name">Phone Number</label>
                </div>

                <div class="input-field col s6">
                  <input type="number" class="validate" name="pin_Code" id="pin_Code" required="True" maxlength="6" onkeyup="autofill1_check(this);return false;" data-url="{% url 'service:autofill1_check' %}"/>
                  <label for="last_name">Pincode</label>
                </div>

                <div class="input-field col s6">
                  <input type="text" name="city" id="city"/>
                  <label for="last_name">City</label>
                </div>

                <div class="input-field col s6">
                  <select class="browser-default" name="select2" id="select2">
                  <option value="1">select</option>
                  <option value="2">Rude Operator</option>
                  <option value="3">Operator denying enrollment</option>
                  <option value="4">Ackwnoledgement receipt not provided</option>
                  <option value="5">Form not available</option>
                  <option value="6">Operator staff not available</option>
                  <option value="7">Inadequate facilities in premises</option>
                  <option value="8">Operator entering incorrect data despite being alerted</option>
                  <option value="9">Agency not available despite mentioning in UIDAI website</option>
                  <option value="10">Corruption</option>
          				<option value="11">Delivery issues</option>
                  </select>
              </div>

              <div class="input-field col s6">
                <input type="text" name="Remarks" id="Remarks" placeholder="Remarks" required="True">
                <label for="last_name">Remarks</label>
              </div>

              <div class="col s6">
                {{form}}
              </div>
                <button type="submit" name="button">Submit</button>
            </div>
          </form>
      </div>
    </div>
  </body>
</html>

templates/update_verify.html
{% extends 'test.html' %}

{% block content %}

  <div class="container">
    <h5></h5>
      <div class="card hoverable">
        {% for x,y,z in update_verify_result %}
          {{ x }}
          {{ y }}
          <embed src="{{ z }}">
        {% endfor%}
      </div>
  </div>
{% endblock %}

templates/verified_mobile_email.html
{% extends 'test.html' %}

{% block content %}

  <div class="container">
    <h5>Verification Status</h5>
    <div class="card hoverable">
      {% if verify_email %}
        Email: {{ email }}<br/>
        Status: {{ msg }}
      {% endif %}
      {% if verify_mobile %}
        Phone Number: {{ mobile }}<br/>
        Status: {{ msg }}
      {% endif %}
    </div>
  </div>

{% endblock %}

templates/verify_otp.html
{% extends 'test.html' %}

{% block content %}

  <div class="container">
    <h5>Verification</h5>
    <div class="card hoverable">
      <form class="" action="{% url 'service:verify_otp' %}" method="post">
        {% csrf_token %}
      <input type="hidden" name="aadhar_num" value="{{ aadhar_num }}"/>
      {% if 'email' %}
        <input type="hidden" name="email" value="{{ email }}"/>
      {% endif %}
      {% if 'number' %}
        <input type="hidden" name="number" value="{{ number }}"/>
      {% endif %}
        Enter OTP: <input type="number" name="otp" id="otp" maxlength="6">
        <div class="card-content grey lighten-4">
          <button type="submit" name="button" class="waves-effect waves-light btn Center">Verify</button>
        </div>
      </form>
  </div>
</div>
{% endblock %}